### PR TITLE
Fix trackid comparison

### LINKED ISSUE #26: Stopped working on Polybar latest update
I am unable to figure out what's going on, as the daemon is running and `spotifyctl` is giving the correct output, yet, for some reason, Polybar is showing blank everywhere.

Here's the relevant portion of the Polybar configuration file:
```
(...)

modules-left = left1 playpause spotify left2

(...)

;; SPOTIFY
[module/playpause]
type = custom/ipc
format-font = 2
format-underline = #1db954
format-background = ${color.shade2}
; Default
hook-0 = echo "  No Song is Playing"
; Playing
hook-1 = echo ""
; Paused
hook-2 = echo ""
click-left = "spotifyctl -q playpause"


[module/spotify]
type = custom/ipc
format-underline = #1db954
format-background = ${color.shade2}
; Default
hook-0 = echo ""
; Playing/paused
hook-1 = spotifyctl -q status
```

And here's the output when running Polybar on the terminal:
```terminal
$ polybar
notice: Parsing config file: /home/undercover/.config/polybar/config.ini
notice: Listening for IPC messages (PID: 5499)
warn: The config parameter 'settings.throttle-input-for' is deprecated, it will be removed in the future. Please remove it from your config
warn: The config parameter 'settings.throttle-output' is deprecated, it will be removed in the future. Please remove it from your config
warn: The config parameter 'settings.throttle-output-for' is deprecated, it will be removed in the future. Please remove it from your config
notice: Loading module 'left1' of type 'custom/text'
notice: Loading module 'playpause' of type 'custom/ipc'
notice: Loading module 'spotify' of type 'custom/ipc'
notice: Loading module 'left2' of type 'custom/text'
notice: Loading module 'workspaces' of type 'internal/xworkspaces'
notice: Loading module 'right5' of type 'custom/text'
notice: Loading module 'pulseaudio' of type 'internal/pulseaudio'
notice: pulseaudio: using default sink alsa_output.pci-0000_00_1f.3.analog-stereo
notice: Loading module 'right4' of type 'custom/text'
notice: Loading module 'battery' of type 'internal/battery'
notice: Loading module 'right3' of type 'custom/text'
notice: Loading module 'backlight' of type 'internal/backlight'
notice: Loading module 'right2' of type 'custom/text'
notice: Loading module 'network' of type 'internal/network'
notice: Loading module 'right1' of type 'custom/text'
notice: Loading module 'date' of type 'internal/date'
notice: Loaded 15 modules
notice: Loaded font "Roboto Mono:size=8" (name=Noto Sans, offset=2, file=/usr/share/fonts/noto/NotoSans-Regular.ttf)
notice: Loaded font "Siji:size=12" (name=Siji, offset=2, file=/usr/share/fonts/misc/siji.bdf)
notice: Loaded font "Iosevka Nerd Font:style=Medium:size=16" (name=Iosevka, offset=3, file=/usr/share/fonts/TTF/Iosevka Medium Nerd Font Complete.ttf)
notice: Loaded font "Font Awesome 6 Free:size=14" (name=Font Awesome 6 Free, offset=2, file=/usr/share/fonts/TTF/fa-regular-400.ttf)
error: tray: Failed to put tray above 0x1400001 in the stack (XCB_MATCH (8))
```

As you can see, everything seems to be alright.

Any tips or ideas on how to proceed the debugging?
Seems to me that I'm missing something quite obvious since it's working on one side and not on the other, yet, I have changed nothing during the update.

### PR DESCRIPTION
**Pull request by FryDay**
Fixes #26

### CODE REVIEW

**Comment by FryDay** [comment]
@mihirlad55 If we could get this reviewed and merged, it would fix everyone's issues that use the AUR package. As it stands, the module is completely broken.

**Comment by mihirlad55** [comment]
I'm gonna be busy today, but I'll try to review tomorrow. Thanks for the PR

**Comment by mihirlad55** [comment]
I reviewed the PR and tested the module. This seems to be 90% of a fix. It fixes the issue with not detecting spotify, so the polybar module will show the player controls and track info. Also, the track info will automatically be updated as the track changes and the controls work for playing/pausing and going to the next/previous track. The only thing that seems to not work is updating the module when the song Play/Pause status is changed (i.e. change pause icon to play when the song is paused and vice versa).

Comparing the DBus messaging changes by spotify with previous versions, it seems spotify no longer publishes Metadata information when the track status changes. As a result, the `is_spotify` check in the code fails, and the following block of code never runs:

**Comment by mihirlad55** [comment]
I think what I'll do is merge this in, so people have at least a mostly functioning module. And we can work on a fix for the rest of the issue. I'll keep the linked issue open until the module is fully fixed.

**Pull request merged**
